config/routes.rb
Rails.application.routes.draw do

  root 'visitors#index'
  resources :showings do
    member do
      get 'tickets_sold'
    end
  end
  get "/tickets" => 'tickets#index'
  get "/admin" => 'admins#index'
  post "/tickets" => 'showings#make_ticket'
  
end

app/models/showing.rb
class Showing < ActiveRecord::Base
	has_many :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :showing

	validates :name, :cc_exp, presence: true, length: { minimum: 4, maximum: 20 }
	validates :email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
	validates :cc_num, presence: true, length: { minimum: 6, maximum: 20 }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @upcoming_showings = Showing.order("time ASC").where(["time > ?", Time.now])
    @past_showings = Showing.order("time DESC").where(["time < ?", Time.now])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  def index
  end

  def new
  	@showing = Showing.new
  end

  def create
  	@showing = Showing.create(showing_params)

  	if @showing.save
  		redirect_to @showing
  	else
  		flash[:alert] = "Failed to Create!!"
  		redirect_to :back
  	end
  end

  def show
  	@showing = Showing.find(params[:id])
  	@ticket = Ticket.new
  end

  def make_ticket
  	@ticket = Ticket.new(ticket_params)

  	if @ticket.save
  		showing = @ticket.showing
  		showing.seat_count -= 1
  		showing.save
  		TicketMailer.receipt(@ticket).deliver_now
  		flash[:notice] = "Ticket Purchased!"
  		redirect_to :root
  	else
  		flash[:alert] = "Please Provide Proper Name, Email, and Credit Card Info"
  		redirect_to :back
  	end
  end

  def tickets_sold
  	@showing = Showing.find(params[:id])
  end

  def edit
  	@showing = Showing.find(params[:id])
  end

  def update
  	@showing = Showing.find(params[:id])

  	if @showing.update(showing_params)
  		redirect_to @showing
  	else
  		flash[:alert] = "Failed to Update!!"
			redirect_to @showing
		end
  end

  private

	def showing_params
	  params.require(:showing).permit(:title, :time, :seat_count, :auditorium)
	end

	def ticket_params
	  params.require(:ticket).permit(:name, :email, :cc_num, :cc_exp, :showing_id)
	end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @showings = Showing.order("time ASC").where(["time > ?", Time.now])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4 text-center">
      <h4>Admin Dashboard</h4>
      <p>Here you can view upcoming and past movie showings, and you can click on a showing to view its tickets that were sold.  Click on the button bellow to create a new showing.  If you're not authorized to be here then you better leave immediately!</p>
      <%= link_to "Click to Create a New Showing!", new_showing_path, class: "btn btn-primary page-scroll" %>
      <h6>To view all tickets ever sold regardless of particular showing, <%= link_to "click here", tickets_path %>.
    </div>
  </div>

  <hr>

  <div class="container col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <h2 class="text-center">Upcoming Showings
    <br>
      
    <br>

      <table class="table table-striped">
        <thead >
          <tr>

          </tr>
        </thead>
        <tbody>

            <% @upcoming_showings.each do |showing| %>
            <tr>

              <td><div class="text-center">
                  <!-- <hr> -->
                  <h4><%= showing.title %></h4>
                  <h4><%= showing.time.localtime.to_formatted_s(:short)   %></h4>
                  <h4>Seats Remaining: <%= showing.seat_count %></h4>
                  <% if showing.tickets.count > 0 %>
                    <%= link_to "View Tickets Sold", tickets_sold_showing_path(showing), class: "btn btn-primary btn-sm"  %>
                  <% else %>
                    <h5>No Tickets Sold</h5>
                  <% end %>
                  <%= link_to "Edit", edit_showing_path(showing), class: "btn btn-info btn-sm"  %>

              </div></td>

            </tr>

          <% end %>
      
        </tbody>

      </table>

  </div>


  <div class="container col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <h2 class="text-center">Past Showings
    <br>
      
    <br>

      <table class="table table-striped">
        <thead >
          <tr>

          </tr>
        </thead>
        <tbody>

            <% @past_showings.each do |showing| %>
            <tr>

              <td><div class="text-center">
                  <!-- <hr> -->
                  <h4><%= showing.title %></h4>
                  <h4><%= showing.time.localtime.to_formatted_s(:short)   %></h4>
                  <h4>Seats Remaining: <%= showing.seat_count %></h4>
                  <% if showing.tickets.count > 0 %>
                    <%= link_to "View Tickets Sold", tickets_sold_showing_path(showing), class: "btn btn-primary btn-sm"  %>
                  <% else %>
                    <h5>No Tickets Sold</h5>
                  <% end %>

              </div></td>

            </tr>

          <% end %>
      
        </tbody>

      </table>

  </div>
</body>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Admin Board', admin_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Eric's Theater" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Eric's Theater" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/showings/edit.html.erb
<br>
<div class="row">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
		<%= simple_form_for @showing do |f| %>
		  
		  <%= f.input :title, label: "Movie Title" %>
			<%= f.input :time, as: :datetime %>
		  <%= f.input :seat_count %>
		  <%= f.input :auditorium, collection: [ 1,2,3 ] %>
		  <%= f.button :submit %>
		<% end %>
	</div>
</div>

app/views/showings/new.html.erb
<br>
<div class="row">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
		<%= simple_form_for @showing do |f| %>
		  
		  <%= f.input :title, label: "Movie Title" %>
			<%= f.input :time, as: :datetime %>
		  <%= f.input :seat_count %>
		  <%= f.input :auditorium, collection: [ 1,2,3 ] %>
		  <%= f.button :submit %>
		<% end %>
	</div>
</div>

app/views/showings/show.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
		<hr>
		<p>
		  Title:
		  <strong><%= @showing.title %></strong>
		</p>
		 
		<p>
		  Time:
		  <strong><%= @showing.time.localtime.to_formatted_s(:short) %></strong>
		</p>
		<p>
		  Seats Remaining:
		  <strong><%= @showing.seat_count %></strong>
		</p>
		<p>
		  Auditorium:
		  <strong><%= @showing.auditorium %></strong>
		</p>
		<br>
		
	</div>
</div>

<hr>
<% unless @showing.seat_count == 0 %>
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
			<h2>Buy Your Ticket</h2>
			<h4>Price: $10.00</h4>
			<%= simple_form_for @ticket, url: tickets_path do |f| %>

			  <%= f.error_notification %>
			  <%= f.input :name, label: "Your Name", required: true, error: "Required Field" %>
				<%= f.input :email, label: "Your Email", required: true, error: "Required Field" %>
			  <%= f.input :cc_num, label: "Credit Card Number", required: true, error: "Required Field" %>
			  <%= f.input :cc_exp, label: "Credit Card Experation", required: true, placeholder: "mm/yy", error: "Required Field" %>
			  <%= f.input :showing_id, as: :hidden, input_html: { value: @showing.id } %>
			  <%= f.button :submit, "Buy Ticket" %>
			<% end %>

		</div>
	</div>
<% end %>

app/views/showings/tickets_sold.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
		<hr>
		<p>
		  Title:
		  <strong><%= @showing.title %></strong>
		</p>
		 
		<p>
		  Time:
		  <strong><%= @showing.time.localtime.to_formatted_s(:short) %></strong>
		</p>
		<p>
		  Seats Remaining:
		  <strong><%= @showing.seat_count %></strong>
		</p>
		<p>
		  Auditorium:
		  <strong><%= @showing.auditorium %></strong>
		</p>
		<p>
		  Price:
		  <strong>$10.00</strong>
		</p>
		<br>
		<% unless @showing.time < Time.now %>
			<%= button_to "Edit", edit_showing_path, method: :get %>
		<% end %>
	</div>
</div>


<table class="table table-bordered">
  <thead>
    <tr>
    	<th>Name</th>
  		<th>Email</th>
    	<th>CC Num/Exp</th>
    </tr>
  </thead>
  <tbody>
  	<% @showing.tickets.each do |ticket| %>
  	<tr>
  	  <td><%= ticket.name %></td>
  	  <td><%= ticket.email %></td>
  	  <td><%= ticket.cc_num %><br><%= ticket.cc_exp %></td>
  	</tr>
  	<% end %>
  </tbody>
</table>

app/views/tickets/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
    	<th>Name/Email</th>
    	<th>CC Num/Exp</th>
      <th>Showing</th>
    </tr>
  </thead>
  <tbody>
  	<% @tickets.each do |ticket| %>
  	<tr>
  	  <td><%= ticket.name %><br><%= ticket.email %></td>
  	  <td><%= ticket.cc_num %><br><%= ticket.cc_exp %></td>
      <% unless ticket.showing == nil %> <!-- some tickets locally have showing_id == nil -->
        <td><%= link_to ticket.showing.title, tickets_sold_showing_path(ticket.showing)  %></td>
      <% end %>
  	</tr>
  	<% end %>
  </tbody>
</table>

app/views/visitors/index.html.erb
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">



  <div class="container">

    <br>

      <div class="row">
          <div class="col-lg-12 text-center">
              <h2>Upcoming Movie Showings</h2>
              <p class="lead">Click on a showing in order to reserve your ticket.</p>
              
          </div>
      </div>
      <!-- /.row -->

      <table class="table table-striped">
        <thead >
          <tr>

          </tr>
        </thead>
        <tbody>

            <% @showings.each do |showing| %>
            <tr>

              <td><div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 text-center">
                  <!-- <hr> -->
                  <h3><%= showing.title %></h3>
                  <h4><%= showing.time.localtime.to_formatted_s(:short)   %></h4>
                  <% if showing.seat_count > 0 %>
                    <%= link_to "Get Tickets", showing_path(showing), class: "btn btn-success"  %>
                  <% else %>
                    <h5><%= link_to "Sold Out", showing_path(showing), style: "color:red;" %></h5>
                  <% end %>

              </div></td>

            </tr>

          <% end %>
      
        </tbody>

      </table>

  </div>
</body>